[package]
name = "cppbuild"
version = "0.1.0"
authors = ["Vanessa McHale <vamchale@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2"
regex = "1"
lazy_static = "1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "cppbuild_bench"
harness = false

[profile.release]
lto = true
